/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tahmazovfarid.resumedesktopapp.main.panels;

import config.Config;
import daoInter.EmpDaoInter;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import model.EmployedHistory;
import model.User;

/**
 *
 * @author TahmazovFarid
 */
public class EmpHistoryPanel extends javax.swing.JPanel {

    EmpDaoInter empDaoInter = Config.empDaoInter;
    User u = Config.loggedInUser;
    List<EmployedHistory> emps = empDaoInter.getAllEmployedHistoryByUserId(u);

    public EmpHistoryPanel() {
        initComponents();
        fillWindow();
    }

    private void fillWindow() {
        for (EmployedHistory emp : emps) {
            headerTxt.setText(emp.getHeader());
            descTxt.setText(emp.getJobDescription());
            beginTxt.setText(emp.getBeginDate().toString());
            endTxt.setText(emp.getEndDate().toString());
        }

    }

    public void getFilledUserEmp(User u) {
        String header = headerTxt.getText();
        String desc = descTxt.getText();
        String beginDateStr = beginTxt.getText();
        String endDateStr = endTxt.getText();

        Date beginDate = strConvertedDate(beginDateStr);
        Date endDate = strConvertedDate(endDateStr);
        EmployedHistory empResult = null;

        List<EmployedHistory> emps = empDaoInter.getAllEmployedHistoryByUserId(u);
        for (EmployedHistory empSet: emps) {
            empSet.setHeader(header);
            empSet.setJobDescription(desc);
            empSet.setBeginDate(beginDate);
            empSet.setEndDate(endDate);
            
            empResult = empSet;
        }
        
        empDaoInter.updateEmployedHistory(empResult);

    }

    private Date strConvertedDate(String dateStr) {
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
        java.util.Date date = null;
        try {
            date = (java.util.Date) simpleDateFormat.parse(dateStr);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.sql.Date dateSql = new java.sql.Date(date.getTime());
        return dateSql;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        descTxt = new javax.swing.JTextArea();
        beginTxt = new javax.swing.JTextField();
        endTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        headerTxt = new javax.swing.JTextField();

        descTxt.setColumns(20);
        descTxt.setRows(5);
        jScrollPane2.setViewportView(descTxt);

        beginTxt.setToolTipText("Begin date");

        endTxt.setToolTipText("End Date");

        jLabel1.setText("Begin dt");

        jLabel2.setText("Descrip");

        jLabel3.setText("Header");

        jLabel4.setText("End date");

        headerTxt.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        headerTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(endTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(headerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {beginTxt, endTxt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(headerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void headerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headerTxtActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beginTxt;
    private javax.swing.JTextArea descTxt;
    private javax.swing.JTextField endTxt;
    private javax.swing.JTextField headerTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
